import uuid from "react-native-uuid";
//top doctor img
import topDoctorImg1 from "../assets/images/top-doctor-1.png";
import topDoctorImg2 from "../assets/images/top-doctor-2.png";
import topDoctorImg3 from "../assets/images/top-doctor-3.png";
import topDoctorImg4 from "../assets/images/top-doctor-4.png";

//friend image
import friendPic1 from "../assets/images/friend-1.png";
import friendPic2 from "../assets/images/friend-2.png";
import friendPic3 from "../assets/images/friend-3.png";
import friendPic4 from "../assets/images/friend-4.png";
import friendPic5 from "../assets/images/friend-5.png";
import friendPic6 from "../assets/images/friend-6.png";

//doctor speciality icon
import specialityIcon1 from "../assets/images/docton-speciality-icon-1.png";
import specialityIcon2 from "../assets/images/docton-speciality-icon-2.png";
import specialityIcon3 from "../assets/images/docton-speciality-icon-3.png";
import specialityIcon4 from "../assets/images/docton-speciality-icon-4.png";
import specialityIcon5 from "../assets/images/docton-speciality-icon-5.png";
import specialityIcon6 from "../assets/images/docton-speciality-icon-6.png";
import specialityIcon7 from "../assets/images/docton-speciality-icon-7.png";
import specialityIcon8 from "../assets/images/docton-speciality-icon-8.png";
import specialityIcon9 from "../assets/images/docton-speciality-icon-9.png";
import specialityIcon10 from "../assets/images/docton-speciality-icon-10.png";

//payment methods
import masterCard from "../assets/images/master-card.png";
import paypal from "../assets/images/paypal.png";
import payoneer from "../assets/images/payoneer.png";
import creditCard from "../assets/images/card.png";
import bank from "../assets/images/bank.png";

//upcoming slider img
// import sliderImg1 from "../assets/images/upcoming-slider-img-1.png";
// import sliderImg2 from "../assets/images/upcoming-slider-img-2.png";
// import sliderImg3 from "../assets/images/upcoming-slider-img-3.png";
// import sliderImg4 from "../assets/images/upcoming-slider-img-4.png";
import sliderImg1 from "../assets/images/doc1.png";
import sliderImg2 from "../assets/images/doc2.png";
import sliderImg3 from "../assets/images/doc3.png";
import sliderImg4 from "../assets/images/doc3.png";

export const onbordingSliderData = [
  {
    id: 1,
    title: "Expert Doctor",
    colorTitle: "Advice Online",
    description:
      "Access professional medical guidance conveniently from the comfort of your home.",
  },
  {
    id: 2,
    title: "Doctor Support, Always",
    colorTitle: "Ready",
    description:
      "Access reliable medical assistance whenever you need it, from trusted professionals.",
  },
  {
    id: 3,
    title: "Stay Healthy, ",
    colorTitle: "Stay Connected",
    description:
      "Stay connected to health resources for a healthier, more informed lifestyle.",
  },
];

export const doctorSpecialityData = [
  {
    id: uuid.v4(),
    icon: "eye",
    title: "Ophthalmologist",
    totalDoctors: "361",
  },
  {
    id: uuid.v4(),
    icon: "medical",
    title: "Neurologist",
    totalDoctors: "381",
  },
  {
    id: uuid.v4(),
    icon: "eye",
    title: "Cardiologists",
    totalDoctors: "241",
  },
  {
    id: uuid.v4(),
    icon: "medical",
    title: "Dermatologists",
    totalDoctors: "91",
  },
];

export const topDoctorData = [
  {
    id: uuid.v4(),
    name: "Dr. Marvin McKinney",
    img: topDoctorImg1,
    department: "Cardiologist",
    medicalName: "JFK Medical",
    rating: "4.3",
    availableTime: "12pm-5pm",
    fee: "40",
    slots: {},
    speciality: "General Dentist",
  },
  {
    id: uuid.v4(),
    name: "Dr. Dianne Russell",
    img: topDoctorImg2,
    department: "Neorologist",
    medicalName: "Dhaka Medical",
    rating: "4.5",
    availableTime: "12pm-5pm",
    fee: "48",
    slots: {
      "1": [
        {
          "slotName": "Morning",
        },
        {
          "slotName": "Morning2",
        },
      ]
    },
    speciality: "General Dentist",
  },
  {
    id: uuid.v4(),
    name: "Dr. Marvin McKinney",
    img: topDoctorImg3,
    department: "Urologist",
    medicalName: "Birdem Medical",
    rating: "4.2",
    availableTime: "12pm-5pm",
    fee: "53",
    slots: {},
    speciality: "General Dentist",
  },
  {
    id: uuid.v4(),
    name: "Dr. Savannah Nguyen",
    img: topDoctorImg4,
    department: "Immunologist",
    medicalName: "PG Hospital",
    rating: "4.7",
    availableTime: "12pm-5pm",
    fee: "55",
    slots: {},
    speciality: "General Dentist",
  },
];

export const servicesList = [
  {
    id: uuid.v4(),
    img: friendPic1,
    name: "Jane Cooper",
    message: "Hi Cooper how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic2,
    name: "Gerald Hernandez",
    message: "Hi Gerald how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic3,
    name: "Martin Santos",
    message: "Hi Martin how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic4,
    name: "Ethan Greer",
    message: "Hi Ethan how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic5,
    name: "Birdie Perry",
    message: "Hi Birdie how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic6,
    name: "Lela Lindsey",
    message: "Hi Lela how are you...",
  },
];


export const serviceData = [
  {
    id: 1,
    serviceNameAr: "طب أسنان الأسرة",
    serviceNameEn: "Family Dentistry",
  },
  {
    id: 2,
    serviceNameAr: "اللثة",
    serviceNameEn: "Family Dentistry",
  },
  {
    id: 3,
    serviceNameAr: "طب الأسنان الحفظي",
    serviceNameEn: "Family Dentistry",
  },
  {
    id: 4,
    serviceNameAr: "طب الأسنان الوقائي",
    serviceNameEn: "Maxillofacial Surgery and Implantology",
  },
]


export const friendChatList = [
  {
    id: uuid.v4(),
    img: friendPic1,
    name: "Jane Cooper",
    message: "Hi Cooper how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic2,
    name: "Gerald Hernandez",
    message: "Hi Gerald how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic3,
    name: "Martin Santos",
    message: "Hi Martin how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic4,
    name: "Ethan Greer",
    message: "Hi Ethan how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic5,
    name: "Birdie Perry",
    message: "Hi Birdie how are you...",
  },
  {
    id: uuid.v4(),
    img: friendPic6,
    name: "Lela Lindsey",
    message: "Hi Lela how are you...",
  },
];

export const myAppoinmentData = [
  {
    id: uuid.v4(),
    name: "Dr. Adam Williams",
    img: topDoctorImg1,
    sessionStatus: "Upcoming",
    sessionTyps: "Video Call",
    rating: "4.3",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Erik Hudson",
    img: topDoctorImg2,
    sessionStatus: "Completed",
    sessionTyps: "Audio Call",
    rating: "4.7",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Jim Neal",
    img: topDoctorImg3,
    sessionStatus: "Upcoming",
    sessionTyps: "Video Call",
    rating: "4.5",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Derrick Ferguson",
    img: topDoctorImg4,
    sessionStatus: "Cancelled",
    sessionTyps: "Chat Session",
    rating: "4.3",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Eula Byrd",
    img: topDoctorImg1,
    sessionStatus: "Upcoming",
    sessionTyps: "Video Call",
    rating: "4.4",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Katharine Hansen",
    img: topDoctorImg2,
    sessionStatus: "Completed",
    sessionTyps: "Audio Call",
    rating: "4.3",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Alfred Lyons",
    img: topDoctorImg3,
    sessionStatus: "Cancelled",
    sessionTyps: "Video Call",
    rating: "4.2",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Lula Lyons",
    img: topDoctorImg4,
    sessionStatus: "Cancelled",
    sessionTyps: "Chat Session",
    rating: "4.3",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },

  {
    id: uuid.v4(),
    name: "Dr. Georgia Lewis",
    img: topDoctorImg1,
    sessionStatus: "Completed",
    sessionTyps: "Video Call",
    rating: "4.9",
    speciality: "General Dentist",
    availableTime: "12pm-5pm",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Maggie Robertson",
    img: topDoctorImg2,
    sessionStatus: "Cancelled",
    sessionTyps: "Chat Session",
    rating: "4.3",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Carl King",
    img: topDoctorImg3,
    sessionStatus: "Upcoming",
    sessionTyps: "Video Call",
    rating: "4.5",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
  {
    id: uuid.v4(),
    name: "Dr. Sue Copeland",
    img: topDoctorImg4,
    sessionStatus: "Completed",
    sessionTyps: "Audio Call",
    rating: "4.3",
    availableTime: "12pm-5pm",
    speciality: "General Dentist",
    branchName: "",
    practitionerName: "",
    department: "",
    hisStatus: "",
    age: 0,
    startTime: "",
    endTime: "",
    slots: [],
  },
];

export const profileSettings = [
  // {
  //   id: 1,
  //   icon: "notifications-outline",
  //   name: "Notification",
  //   link: "/NotificationSettings",
  // },
  {
    id: 2,
    icon: "receipt-outline",
    name: "My Invoices",
    link: "/MyInvoices",
  },
  {
    id: 3,
    icon: "document-text-outline",
    name: "My Prescription",
    link: "/MyPrescription",
  },
  // {
  //   id: 4,
  //   icon: "card-outline",
  //   name: "Payment",
  //   link: "/AddCardPage",
  // },
  // {
  //   id: 4,
  //   icon: "lock-closed-outline",
  //   name: "Security",
  //   link: "/ChangePassword",
  // },
  {
    id: 5,
    icon: "language-outline",
    name: "Language",
    link: "/LanguageSettings",
  },
  // {
  //   id: 7,
  //   icon: "sunny-outline",
  //   name: "Dark Mode",
  //   link: "/NotificationSettings",
  // },
  {
    id: 6,
    icon: "person",
    name: "About Us",
    link: "/AboutUs",
  },
  {
    id: 7,
    icon: "help",
    name: "Help Center",
    link: "/HelpSupport",
  },
];

export const scheduleDates = [
  {
    date: "7",
    day: "Sat",
  },
  {
    date: "8",
    day: "Sun",
  },
  {
    date: "9",
    day: "Mon",
  },
  {
    date: "10",
    day: "Tue",
  },
  {
    date: "11",
    day: "Wed",
  },
  {
    date: "12",
    day: "Thu",
  },
  {
    date: "13",
    day: "Fri",
  },
  {
    date: "14",
    day: "Sat",
  },
  {
    date: "15",
    day: "Sun",
  },
];

export const doctorSpecialityData2 = [
  {
    name: "Surgeon",
    img: specialityIcon1,
    totalDoctor: "934",
  },
  {
    name: "Physician",
    img: specialityIcon2,
    totalDoctor: "527",
  },
  {
    name: "Pediatrician",
    img: specialityIcon3,
    totalDoctor: "382",
  },
  {
    name: "Gynecologist",
    img: specialityIcon4,
    totalDoctor: "247",
  },
  {
    name: "Cardiologist",
    img: specialityIcon5,
    totalDoctor: "727",
  },
  {
    name: "Dermatologist",
    img: specialityIcon6,
    totalDoctor: "717",
  },
  {
    name: "Neurologist",
    img: specialityIcon7,
    totalDoctor: "659",
  },
  {
    name: "Psychiatrist",
    img: specialityIcon8,
    totalDoctor: "123",
  },
  {
    name: "Oncologist",
    img: specialityIcon9,
    totalDoctor: "680",
  },
  {
    name: "Radiologist",
    img: specialityIcon10,
    totalDoctor: "097",
  },
];

export const feesInformation = [
  {
    name: "Voice Call",
    desc: "Can make a video call with doctor",
    price: "35",
  },
  {
    name: "Audio Call",
    desc: "Can make a voice call with doctor",
    price: "25",
  },
  {
    name: "Chat Session",
    desc: "Can make a chat session with doctor",
    price: "12",
  },
];

export const paymentMethods = [
  {
    name: "Paypal",
    img: paypal,
  },
  {
    name: "Payoneer",
    img: payoneer,
  },
  {
    name: "Bank Transfer",
    img: bank,
  },
  {
    name: "Mastercard",
    img: masterCard,
  },
  {
    name: "Credit Card",
    img: creditCard,
  },
];

export const faqData = [
  {
    id: 1,
    question: "What is Appoinx?",
    answer:
      "Appoinx is greatest medical online consultation app platform in this century",
  },
  {
    id: 2,
    question: "How to use Appoinx?",
    answer:
      "Appoinx is greatest medical online consultation app platform in this century",
  },
  {
    id: 3,
    question: "How to schedule consultation on Appoinx?",
    answer:
      "Appoinx is greatest medical online consultation app platform in this century",
  },
  {
    id: 4,
    question: "How to logout from Appoinx?",
    answer:
      "Appoinx is greatest medical online consultation app platform in this century",
  },
  {
    id: 5,
    question: "Is there a free tips to get health in this app?",
    answer:
      "Appoinx is greatest medical online consultation app platform in this century",
  },

  {
    id: 6,
    question: "Is Appoinx free to use?",
    answer:
      "Appoinx is greatest medical online consultation app platform in this century",
  },
];

export const upcomingSliderData = [
  {
    id: 1,
    title: "Liposuction (Minor)",
    desc: "National Day Offer",
    img: sliderImg1,
  },
  {
    id: 2,
    title: "",
    desc: "Mohters Day SSC",
    img: sliderImg2,
  },
  {
    id: 3,
    title: "LHR Full Body",
    desc: "Dr. Daliya Friday",
    img: sliderImg3,
  },
  {
    id: 4,
    title: "LHR Back and Chest",
    desc: "Dr. Daliya Friday",
    img: sliderImg4,
  },
];

export const countries = [ 
  {name: "Afghanistan", code: "AF"}, 
  {name: "land Islands", code: "AX"}, 
  {name: "Albania", code: "AL"}, 
  {name: "Algeria", code: "DZ"}, 
  {name: "American Samoa", code: "AS"}, 
  {name: "AndorrA", code: "AD"}, 
  {name: "Angola", code: "AO"}, 
  {name: "Anguilla", code: "AI"}, 
  {name: "Antarctica", code: "AQ"}, 
  {name: "Antigua and Barbuda", code: "AG"}, 
  {name: "Argentina", code: "AR"}, 
  {name: "Armenia", code: "AM"}, 
  {name: "Aruba", code: "AW"}, 
  {name: "Australia", code: "AU"}, 
  {name: "Austria", code: "AT"}, 
  {name: "Azerbaijan", code: "AZ"}, 
  {name: "Bahamas", code: "BS"}, 
  {name: "Bahrain", code: "BH"}, 
  {name: "Bangladesh", code: "BD"}, 
  {name: "Barbados", code: "BB"}, 
  {name: "Belarus", code: "BY"}, 
  {name: "Belgium", code: "BE"}, 
  {name: "Belize", code: "BZ"}, 
  {name: "Benin", code: "BJ"}, 
  {name: "Bermuda", code: "BM"}, 
  {name: "Bhutan", code: "BT"}, 
  {name: "Bolivia", code: "BO"}, 
  {name: "Bosnia and Herzegovina", code: "BA"}, 
  {name: "Botswana", code: "BW"}, 
  {name: "Bouvet Island", code: "BV"}, 
  {name: "Brazil", code: "BR"}, 
  {name: "British Indian Ocean Territory", code: "IO"}, 
  {name: "Brunei Darussalam", code: "BN"}, 
  {name: "Bulgaria", code: "BG"}, 
  {name: "Burkina Faso", code: "BF"}, 
  {name: "Burundi", code: "BI"}, 
  {name: "Cambodia", code: "KH"}, 
  {name: "Cameroon", code: "CM"}, 
  {name: "Canada", code: "CA"}, 
  {name: "Cape Verde", code: "CV"}, 
  {name: "Cayman Islands", code: "KY"}, 
  {name: "Central African Republic", code: "CF"}, 
  {name: "Chad", code: "TD"}, 
  {name: "Chile", code: "CL"}, 
  {name: "China", code: "CN"}, 
  {name: "Christmas Island", code: "CX"}, 
  {name: "Cocos (Keeling) Islands", code: "CC"}, 
  {name: "Colombia", code: "CO"}, 
  {name: "Comoros", code: "KM"}, 
  {name: "Congo", code: "CG"}, 
  {name: "Congo, The Democratic Republic of the", code: "CD"}, 
  {name: "Cook Islands", code: "CK"}, 
  {name: "Costa Rica", code: "CR"}, 
  {name: "Cote D\"Ivoire", code: "CI"}, 
  {name: "Croatia", code: "HR"}, 
  {name: "Cuba", code: "CU"}, 
  {name: "Cyprus", code: "CY"}, 
  {name: "Czech Republic", code: "CZ"}, 
  {name: "Denmark", code: "DK"}, 
  {name: "Djibouti", code: "DJ"}, 
  {name: "Dominica", code: "DM"}, 
  {name: "Dominican Republic", code: "DO"}, 
  {name: "Ecuador", code: "EC"}, 
  {name: "Egypt", code: "EG"}, 
  {name: "El Salvador", code: "SV"}, 
  {name: "Equatorial Guinea", code: "GQ"}, 
  {name: "Eritrea", code: "ER"}, 
  {name: "Estonia", code: "EE"}, 
  {name: "Ethiopia", code: "ET"}, 
  {name: "Falkland Islands (Malvinas)", code: "FK"}, 
  {name: "Faroe Islands", code: "FO"}, 
  {name: "Fiji", code: "FJ"}, 
  {name: "Finland", code: "FI"}, 
  {name: "France", code: "FR"}, 
  {name: "French Guiana", code: "GF"}, 
  {name: "French Polynesia", code: "PF"}, 
  {name: "French Southern Territories", code: "TF"}, 
  {name: "Gabon", code: "GA"}, 
  {name: "Gambia", code: "GM"}, 
  {name: "Georgia", code: "GE"}, 
  {name: "Germany", code: "DE"}, 
  {name: "Ghana", code: "GH"}, 
  {name: "Gibraltar", code: "GI"}, 
  {name: "Greece", code: "GR"}, 
  {name: "Greenland", code: "GL"}, 
  {name: "Grenada", code: "GD"}, 
  {name: "Guadeloupe", code: "GP"}, 
  {name: "Guam", code: "GU"}, 
  {name: "Guatemala", code: "GT"}, 
  {name: "Guernsey", code: "GG"}, 
  {name: "Guinea", code: "GN"}, 
  {name: "Guinea-Bissau", code: "GW"}, 
  {name: "Guyana", code: "GY"}, 
  {name: "Haiti", code: "HT"}, 
  {name: "Heard Island and Mcdonald Islands", code: "HM"}, 
  {name: "Holy See (Vatican City State)", code: "VA"}, 
  {name: "Honduras", code: "HN"}, 
  {name: "Hong Kong", code: "HK"}, 
  {name: "Hungary", code: "HU"}, 
  {name: "Iceland", code: "IS"}, 
  {name: "India", code: "IN"}, 
  {name: "Indonesia", code: "ID"}, 
  {name: "Iran, Islamic Republic Of", code: "IR"}, 
  {name: "Iraq", code: "IQ"}, 
  {name: "Ireland", code: "IE"}, 
  {name: "Isle of Man", code: "IM"}, 
  {name: "Israel", code: "IL"}, 
  {name: "Italy", code: "IT"}, 
  {name: "Jamaica", code: "JM"}, 
  {name: "Japan", code: "JP"}, 
  {name: "Jersey", code: "JE"}, 
  {name: "Jordan", code: "JO"}, 
  {name: "Kazakhstan", code: "KZ"}, 
  {name: "Kenya", code: "KE"}, 
  {name: "Kiribati", code: "KI"}, 
  {name: "Korea, Democratic People\"S Republic of", code: "KP"}, 
  {name: "Korea, Republic of", code: "KR"}, 
  {name: "Kuwait", code: "KW"}, 
  {name: "Kyrgyzstan", code: "KG"}, 
  {name: "Lao People\"S Democratic Republic", code: "LA"}, 
  {name: "Latvia", code: "LV"}, 
  {name: "Lebanon", code: "LB"}, 
  {name: "Lesotho", code: "LS"}, 
  {name: "Liberia", code: "LR"}, 
  {name: "Libyan Arab Jamahiriya", code: "LY"}, 
  {name: "Liechtenstein", code: "LI"}, 
  {name: "Lithuania", code: "LT"}, 
  {name: "Luxembourg", code: "LU"}, 
  {name: "Macao", code: "MO"}, 
  {name: "Macedonia, The Former Yugoslav Republic of", code: "MK"}, 
  {name: "Madagascar", code: "MG"}, 
  {name: "Malawi", code: "MW"}, 
  {name: "Malaysia", code: "MY"}, 
  {name: "Maldives", code: "MV"}, 
  {name: "Mali", code: "ML"}, 
  {name: "Malta", code: "MT"}, 
  {name: "Marshall Islands", code: "MH"}, 
  {name: "Martinique", code: "MQ"}, 
  {name: "Mauritania", code: "MR"}, 
  {name: "Mauritius", code: "MU"}, 
  {name: "Mayotte", code: "YT"}, 
  {name: "Mexico", code: "MX"}, 
  {name: "Micronesia, Federated States of", code: "FM"}, 
  {name: "Moldova, Republic of", code: "MD"}, 
  {name: "Monaco", code: "MC"}, 
  {name: "Mongolia", code: "MN"}, 
  {name: "Montenegro", code: "ME"},
  {name: "Montserrat", code: "MS"},
  {name: "Morocco", code: "MA"}, 
  {name: "Mozambique", code: "MZ"}, 
  {name: "Myanmar", code: "MM"}, 
  {name: "Namibia", code: "NA"}, 
  {name: "Nauru", code: "NR"}, 
  {name: "Nepal", code: "NP"}, 
  {name: "Netherlands", code: "NL"}, 
  {name: "Netherlands Antilles", code: "AN"}, 
  {name: "New Caledonia", code: "NC"}, 
  {name: "New Zealand", code: "NZ"}, 
  {name: "Nicaragua", code: "NI"}, 
  {name: "Niger", code: "NE"}, 
  {name: "Nigeria", code: "NG"}, 
  {name: "Niue", code: "NU"}, 
  {name: "Norfolk Island", code: "NF"}, 
  {name: "Northern Mariana Islands", code: "MP"}, 
  {name: "Norway", code: "NO"}, 
  {name: "Oman", code: "OM"}, 
  {name: "Pakistan", code: "PK"}, 
  {name: "Palau", code: "PW"}, 
  {name: "Palestinian Territory, Occupied", code: "PS"}, 
  {name: "Panama", code: "PA"}, 
  {name: "Papua New Guinea", code: "PG"}, 
  {name: "Paraguay", code: "PY"}, 
  {name: "Peru", code: "PE"}, 
  {name: "Philippines", code: "PH"}, 
  {name: "Pitcairn", code: "PN"}, 
  {name: "Poland", code: "PL"}, 
  {name: "Portugal", code: "PT"}, 
  {name: "Puerto Rico", code: "PR"}, 
  {name: "Qatar", code: "QA"}, 
  {name: "Reunion", code: "RE"}, 
  {name: "Romania", code: "RO"}, 
  {name: "Russian Federation", code: "RU"}, 
  {name: "RWANDA", code: "RW"}, 
  {name: "Saint Helena", code: "SH"}, 
  {name: "Saint Kitts and Nevis", code: "KN"}, 
  {name: "Saint Lucia", code: "LC"}, 
  {name: "Saint Pierre and Miquelon", code: "PM"}, 
  {name: "Saint Vincent and the Grenadines", code: "VC"}, 
  {name: "Samoa", code: "WS"}, 
  {name: "San Marino", code: "SM"}, 
  {name: "Sao Tome and Principe", code: "ST"}, 
  {name: "Saudi Arabia", code: "SA"}, 
  {name: "Senegal", code: "SN"}, 
  {name: "Serbia", code: "RS"}, 
  {name: "Seychelles", code: "SC"}, 
  {name: "Sierra Leone", code: "SL"}, 
  {name: "Singapore", code: "SG"}, 
  {name: "Slovakia", code: "SK"}, 
  {name: "Slovenia", code: "SI"}, 
  {name: "Solomon Islands", code: "SB"}, 
  {name: "Somalia", code: "SO"}, 
  {name: "South Africa", code: "ZA"}, 
  {name: "South Georgia and the South Sandwich Islands", code: "GS"}, 
  {name: "Spain", code: "ES"}, 
  {name: "Sri Lanka", code: "LK"}, 
  {name: "Sudan", code: "SD"}, 
  {name: "Suriname", code: "SR"}, 
  {name: "Svalbard and Jan Mayen", code: "SJ"}, 
  {name: "Swaziland", code: "SZ"}, 
  {name: "Sweden", code: "SE"}, 
  {name: "Switzerland", code: "CH"}, 
  {name: "Syrian Arab Republic", code: "SY"}, 
  {name: "Taiwan, Province of China", code: "TW"}, 
  {name: "Tajikistan", code: "TJ"}, 
  {name: "Tanzania, United Republic of", code: "TZ"}, 
  {name: "Thailand", code: "TH"}, 
  {name: "Timor-Leste", code: "TL"}, 
  {name: "Togo", code: "TG"}, 
  {name: "Tokelau", code: "TK"}, 
  {name: "Tonga", code: "TO"}, 
  {name: "Trinidad and Tobago", code: "TT"}, 
  {name: "Tunisia", code: "TN"}, 
  {name: "Turkey", code: "TR"}, 
  {name: "Turkmenistan", code: "TM"}, 
  {name: "Turks and Caicos Islands", code: "TC"}, 
  {name: "Tuvalu", code: "TV"}, 
  {name: "Uganda", code: "UG"}, 
  {name: "Ukraine", code: "UA"}, 
  {name: "United Arab Emirates", code: "AE"}, 
  {name: "United Kingdom", code: "GB"}, 
  {name: "United States", code: "US"}, 
  {name: "United States Minor Outlying Islands", code: "UM"}, 
  {name: "Uruguay", code: "UY"}, 
  {name: "Uzbekistan", code: "UZ"}, 
  {name: "Vanuatu", code: "VU"}, 
  {name: "Venezuela", code: "VE"}, 
  {name: "Viet Nam", code: "VN"}, 
  {name: "Virgin Islands, British", code: "VG"}, 
  {name: "Virgin Islands, U.S.", code: "VI"}, 
  {name: "Wallis and Futuna", code: "WF"}, 
  {name: "Western Sahara", code: "EH"}, 
  {name: "Yemen", code: "YE"}, 
  {name: "Zambia", code: "ZM"}, 
  {name: "Zimbabwe", code: "ZW"} 
  ]
